# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'MSW2' do

end

target 'MSW2Tests', :exclusive => true do
  pod 'KIF', '~> 3.0', :configurations => ['Debug']

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’

pod 'AFNetworking', '~> 3.0'
end

